### ISSUE TITLE
Crashes when starting offline

### ISSUE THREAD

**Issue by cdelgadob** [orchestrated-io/serverless-plugin-offline-dynamodb-stream#3]
After downloading and configured, it throws an error saying:
`Serverless plugin "serverless-plugin-offline-dynamodb-stream" initialization errored: Cannot find module '/Users/carlos/serverless-project/src/app/handler'`

After enabling 'SLS_DEBUG`I get this:
```
Error --------------------------------------------------

  Cannot find module '/Users/carlos/serverless-project/src/app/handler'

     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.

  Stack Trace --------------------------------------------

Error: Cannot find module '/Users/carlos/serverless-project/src/app/handler'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at ServerlessPluginOfflineDynamodbStream.createHandler (/Users/carlos/serverless-project/node_modules/serverless-plugin-offline-dynamodb-stream/src/index.js:38:21)
    at functions.functions.map (/Users/carlos/serverless-project/node_modules/serverless-plugin-offline-dynamodb-stream/src/index.js:27:27)
    at Array.map (<anonymous>)
    at ServerlessPluginOfflineDynamodbStream.streams.streams.map (/Users/carlos/serverless-project/node_modules/serverless-plugin-offline-dynamodb-stream/src/index.js:25:28)
    at Array.map (<anonymous>)
    at new ServerlessPluginOfflineDynamodbStream (/Users/carlos/serverless-project/node_modules/serverless-plugin-offline-dynamodb-stream/src/index.js:23:28)
    at PluginManager.addPlugin (/Users/carlos/.nvm/versions/node/v8.10.0/lib/node_modules/serverless/lib/classes/PluginManager.js:52:28)
    at plugins.forEach (/Users/carlos/.nvm/versions/node/v8.10.0/lib/node_modules/serverless/lib/classes/PluginManager.js:92:14)
    at Array.forEach (<anonymous>)
    at PluginManager.loadPlugins (/Users/carlos/.nvm/versions/node/v8.10.0/lib/node_modules/serverless/lib/classes/PluginManager.js:88:13)
    at PluginManager.loadServicePlugins (/Users/carlos/.nvm/versions/node/v8.10.0/lib/node_modules/serverless/lib/classes/PluginManager.js:142:10)
    at PluginManager.loadAllPlugins (/Users/carlos/.nvm/versions/node/v8.10.0/lib/node_modules/serverless/lib/classes/PluginManager.js:84:10)
    at service.load.then (/Users/carlos/.nvm/versions/node/v8.10.0/lib/node_modules/serverless/lib/Serverless.js:67:28)
    at <anonymous>
```

Here is the plugin list in my serverless.yml file:
```
plugins:
  - serverless-webpack
  - serverless-mocha-plugin
  - serverless-dynamodb-local
  - serverless-offline-scheduler
  - serverless-s3-local
  - serverless-s3-local-sync
  - serverless-offline
  - serverless-s3-sync
  - serverless-plugin-offline-dynamodb-stream
  - serverless-plugin-scripts
```
And the plugin configuration:
```
  dynamodbStream:
    host: localhost
    port: 8001
    streams:
      - table: ${self:custom.stage}_streaming_table
        functions:
          - idx_updater
  dynamodb:
    start:
      port: 8001
      cors: '*'
      inMemory: true
      migrate: true
      seed: true
```

**Comment by emmkong** [comment]
Hi @cdelgadob ,

This error occur due to the handler function `idx_updater ` not able to locate properly.
From the provided config, your functions should be in format of {file name}.{function name}, e.g `handler.idx_updater` similar to the serverless function handler.

Hope this helped.

**Comment by emmkong** [comment]
Hi @cdelgadob,

I added a demo project to demonstrate how to use this plugin, feel free to have a look.

https://github.com/orchestrated-io/serverless-plugin-offline-dynamodb-stream/tree/master/demo

Please close this issue if this helped in resolving your issue.

**Comment by cdelgadob** [comment]
Hi @emmkong,

Thanks for your examples!

Just a couple of things:

1. `idx_updater`is in fact the name of my serverless function.
2. I'm getting another error complaining about the region now being set.

Please let me know if you need more info, I can't work out what's going on here...

Thanks

 Carlos

**Comment by emmkong** [comment]
Hi @cdelgadob,

I try to reproduce your issue with the demo project by putting the handle.js on the path like you mentioned and I could able to produce the expected result.

Following are the few things you could look at: 
1. ensure you have the latest version of the plugins
2. if '/Users/carlos/serverless-project/src/app/handler.js' exist? or did you used any syntax that your node version currently not supported?
3. Are you using serverless-webpack? if yes, this is a known issue and I will have a look at my next item.

**Comment by cdelgadob** [comment]
That's it, I'm using serverless-webpack. Pls let me know if you have an estimated date for this.

Thanks a lot for your help!

**Comment by emmkong** [comment]
@cdelgadob is the fix helped? Please close this issue if it has been resolved. Thanks

**Comment by giomarino** [comment]
It seems to not be fixed. I use serverless-bundle, I receive this error but a database.js file exists in /Users/user/Projects/example/services/database/.webpack/service/ it contains trackResources function:

```
DynamoDBStreamReadable error... terminating stream... Error => Error: Cannot find module '/Users/user/Projects/example/services/database/.webpack/service/'
Require stack:
- /Users/user/Projects/example/node_modules/serverless-plugin-offline-dynamodb-stream/src/executeFunctions.js
- /Users/user/Projects/example/node_modules/serverless-plugin-offline-dynamodb-stream/src/FunctionExecutable.js
- /Users/user/Projects/example/node_modules/serverless-plugin-offline-dynamodb-stream/src/index.js
- /usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js
- /usr/local/lib/node_modules/serverless/lib/Serverless.js
- /usr/local/lib/node_modules/serverless/lib/utils/autocomplete.js
- /usr/local/lib/node_modules/serverless/bin/serverless.js
 
  Error --------------------------------------------------
 
  Error: Cannot find module '/Users/user/Projects/example/services/database/.webpack/service/'
  Require stack:
  - /Users/user/Projects/example/node_modules/serverless-plugin-offline-dynamodb-stream/src/executeFunctions.js
  - /Users/user/Projects/example/node_modules/serverless-plugin-offline-dynamodb-stream/src/FunctionExecutable.js
  - /Users/user/Projects/example/node_modules/serverless-plugin-offline-dynamodb-stream/src/index.js
  - /usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js
  - /usr/local/lib/node_modules/serverless/lib/Serverless.js
  - /usr/local/lib/node_modules/serverless/lib/utils/autocomplete.js
  - /usr/local/lib/node_modules/serverless/bin/serverless.js
      at Function.Module._resolveFilename (internal/modules/cjs/loader.js:797:15)
      at Function.resolve (internal/modules/cjs/helpers.js:80:19)
      at module.exports (/Users/user/Projects/example/node_modules/require-without-cache/index.js:15:28)
      at createHandler (/Users/user/Projects/example/node_modules/serverless-plugin-offline-dynamodb-stream/src/executeFunctions.js:19:19)
      at /Users/user/Projects/example/node_modules/serverless-plugin-offline-dynamodb-stream/src/executeFunctions.js:45:23
      at arrayMap (/Users/user/Projects/example/node_modules/lodash/lodash.js:639:23)
      at map (/Users/user/Projects/example/node_modules/lodash/lodash.js:9580:14)
      at executeFunctions (/Users/user/Projects/example/node_modules/serverless-plugin-offline-dynamodb-stream/src/executeFunctions.js:44:5)
      at Writable.write [as _write] (/Users/user/Projects/example/node_modules/serverless-plugin-offline-dynamodb-stream/src/FunctionExecutable.js:7:7)
      at doWrite (_stream_writable.js:431:12)
      at writeOrBuffer (_stream_writable.js:415:5)
      at Writable.write (_stream_writable.js:305:11)
      at DynamoDBStreamReadable.ondata (_stream_readable.js:727:22)
      at DynamoDBStreamReadable.emit (events.js:210:5)
      at DynamoDBStreamReadable.EventEmitter.emit (domain.js:475:20)
      at addChunk (_stream_readable.js:309:12)
      at readableAddChunk (_stream_readable.js:290:11)
      at DynamoDBStreamReadable.Readable.push (_stream_readable.js:224:10)
      at /Users/user/Projects/example/node_modules/serverless-plugin-offline-dynamodb-stream/src/DynamoDBStreamReadable.js:129:16
      at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

### Custom section
```
custom:
  namespace: HELLO
  namespaceLowercase: hello
  profile: parque
  runtime: nodejs12.x
  region: eu-central-1
  timeout: 12
  deploymentBucket:
    name: hello.deployment.bucket
    versioning: false
  dynamodb:
    stages:
      - dev
    start:
      port: 8000
      inMemory: true
      heapInitial: 200m
      heapMax: 1g
      migrate: true
      seed: true
      convertEmptyValues: true
  dynamodbStream:
    host: localhost
    port: 8000
    region: eu-central-1
    streams:
      - table: HELLO-ResourcesTable
        functions:
          - trackResources
  serverless-offline:
    httpPort: 4100
    lambdaPort: 4000
```

### Plugin
```
plugins:
  - serverless-deployment-bucket
  - serverless-bundle
  - serverless-dynamodb-local
  - serverless-plugin-offline-dynamodb-stream
  - serverless-offline
```

### Functions
```
functions:
  trackResources:
    handler: ./database.trackResources
    description: Track Resources
    events:
      - stream:
          type: dynamodb
          batchSize: 1
          startingPosition: LATEST
          arn:
            !GetAtt ResourcesTable.StreamArn
```

As I said above database.js built file exists on directory, this project is a multiservice monorepo
[
<img width="330" alt="Schermata 2020-10-05 alle 03 41 28" src="https://user-images.githubusercontent.com/65846602/95032966-c98cd380-06bc-11eb-981e-6e94b0a0a593.png">
](url)

### tsconfig
```
{
  "compilerOptions": {
    "baseUrl": ".",
    "lib": ["es2017"],
    "removeComments": true,
    "moduleResolution": "node",
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "sourceMap": true,
    "allowJs": true,
    "target": "es2017",
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "outDir": "../../.build",
    "rootDir": "../.."
  },
  "include": ["./**/*.ts"],
  "exclude": [
    "node_modules/**/*",
    ".serverless/**/*",
    ".webpack/**/*",
    "_warmup/**/*",
    ".vscode/**/*"
  ]
}
```
