### ISSUE TITLE
Don't working with serverless + node + typescript

### ISSUE THREAD

**Issue by gapinto** [orchestrated-io/serverless-plugin-offline-dynamodb-stream#9]
Firstly congratulation! 

I'm working on a POC where I'm using node + typescript + serverless. 

I'm with the same problem related here: [Crashes when starting offline]( https://github.com/orchestrated-io/serverless-plugin-offline-dynamodb-stream/issues/3)

But I believe that the problem here is because the compiled javascript directory is: `./build`

**Comment by emmkong** [comment]
@gapinto you that plugin get root location of the handlers' files from serverless-offlice plugin config. it defaults to the current directory.

```
custom:
  serverless-offline:
    host: 0.0.0.0
    port: 4000
    dontPrintOutput: true
    location: build
```

hope this helped.
